### ISSUE TITLE
Problems with elements dynamically created in the DOM

### ISSUE THREAD

**Issue by yanielbf** [6eDesign/simpleBind.js#1]
Good, first of all my congratulations for this magnificent library. I have problems using simpleBind with a dynamically created element in the DOM using jquery. I would appreciate if you could help me. Regards

**Comment by 6eDesign** [comment]
Thank you, I'm glad you like it so far.  You can call `simpleBind.recollectDOM()` after creating the new element and inserting it into the DOM.  This should collect any new nodes (not containing 'data-simplebindcollected' attribute) and prepare them for binding.

Optionally, you can specify which part of the DOM needs to be recollected.  This is done by passing a parent node of the newly created element(s) to the recollectDOM function.  

Let me know if you have any troubles/questions.  I'll be sure to add this method to the GitHub documentation.

**Comment by 6eDesign** [comment]
@yblancof2 did this help? Happy to provide additional assistance if you ran into any issues - otherwise thinking of closing this issue.
